const mongoose = require('mongoose');
const InventoryItem = require('../models/InventoryItem');
const InventoryTransaction = require('../models/InventoryTransaction');
const AssetAuditLog = require('../models/AssetAuditLog');
const Request = require('../models/Request');
const ReturnRequest = require('../models/ReturnRequest');
const Location = require('../models/Location');
const SerialNumberCounter = require('../models/SerialNumberCounter');
const { logAssetAudit } = require('../services/assetAuditLogService');
const { asyncHandler } = require('../middleware/errorHandler');
const { AppError } = require('../middleware/errorHandler');

// @desc    Get all inventory items
// @route   GET /api/inventory
// @access  Private
const getInventoryItems = asyncHandler(async (req, res) => {
  const page = parseInt(req.query.page) || 1;
  const limit = parseInt(req.query.limit) || 10;
  const skip = (page - 1) * limit;
  const sort = req.query.sort || '-createdAt';
  const search = req.query.search;

  // Build query
  let query = {};
  if (search) {
    query = {
      $or: [
        { uniqueid: { $regex: search, $options: 'i' } },
        { assetname: { $regex: search, $options: 'i' } },
        { productserialnumber: { $regex: search, $options: 'i' } },
        { vendorname: { $regex: search, $options: 'i' } },
        { locationofitem: { $regex: search, $options: 'i' } }
      ]
    };
  }

  // Filter by status if specified
  if (req.query.status) {
    query.status = req.query.status;
  }

  // Filter by category if specified
  if (req.query.category) {
    query.assetcategoryid = req.query.category;
  }

  // Filter by location if specified
  if (req.query.location) {
    query.locationofitem = req.query.location;
  }

  // Filter by condition if specified
  if (req.query.condition) {
    query.conditionofasset = req.query.condition;
  }

  // Filter by stock status
  if (req.query.stockStatus) {
    if (req.query.stockStatus === 'low') {
      query.$expr = { $lte: ['$balancequantityinstock', '$minimumstocklevel'] };
    } else if (req.query.stockStatus === 'out') {
      query.balancequantityinstock = 0;
    } else if (req.query.stockStatus === 'available') {
      query.balancequantityinstock = { $gt: 0 };
    }
  }

  const inventoryItems = await InventoryItem.find(query)
    .populate('assetcategoryid', 'name type')
    .populate('assetid', 'name description')
    .populate('locationid', 'name description address building floor')
    .populate('createdby', 'name email')
    .sort(sort)
    .skip(skip)
    .limit(limit);

  const total = await InventoryItem.countDocuments(query);

  res.json({
    success: true,
    count: inventoryItems.length,
    total,
    page,
    pages: Math.ceil(total / limit),
    data: inventoryItems
  });
});

// @desc    Get single inventory item
// @route   GET /api/inventory/:id
// @access  Private
const getInventoryItem = asyncHandler(async (req, res) => {
  const inventoryItem = await InventoryItem.findById(req.params.id)
    .populate('assetcategoryid', 'name type description')
    .populate('assetid', 'name description manufacturer model')
    .populate('locationid', 'name description address building floor locationType')
    .populate('createdby', 'name email');

  if (!inventoryItem) {
    return res.status(404).json({
      success: false,
      message: 'Inventory item not found'
    });
  }

  res.json({
    success: true,
    data: inventoryItem
  });
});

// Helper function to generate asset code from asset name
const generateAssetCode = (assetName) => {
  if (!assetName) return '---';
  // Take first 3 letters and convert to uppercase, remove non-alphabetic characters
  return assetName.replace(/[^a-zA-Z]/g, '').substring(0, 3).toUpperCase().padEnd(3, '-');
};

/**
 * Generate unique ID with automatically incremented global serial number
 * 
 * Serial numbers are ALWAYS auto-generated by the system based on total asset count.
 * - Each new asset receives the next sequential serial number (001, 002, 003, ...)
 * - Serial numbers increment automatically - no manual input required or allowed
 * - The serial number reflects the total number of assets in the system
 * - Uses atomic counter to ensure no duplicates even under concurrent requests
 * 
 * @param {string} financialyear - Financial year (e.g., "2025-26")
 * @param {string} assetname - Asset name (e.g., "Software")
 * @param {string} locationofitem - Location (e.g., "Storage Room A")
 * @returns {Promise<string>} Unique ID with auto-generated serial number
 */
const generateUniqueIdWithGlobalSerial = async (financialyear, assetname, locationofitem) => {
  // Get next global serial number atomically (automatically increments based on asset count)
  const serialNumber = await SerialNumberCounter.getNextSequence();
  const serialNumberStr = serialNumber.toString().padStart(3, '0');
  
  // Build unique ID: iHUB/{financialyear}/{assetcode}/{location}/{serial}
  let uniqueId = 'iHUB/';
  
  // Add financial year or placeholder
  if (financialyear) {
    uniqueId += financialyear;
  } else {
    uniqueId += '--';
  }
  uniqueId += '/';
  
  // Add asset code or placeholder
  if (assetname) {
    uniqueId += generateAssetCode(assetname);
  } else {
    uniqueId += '---';
  }
  uniqueId += '/';
  
  // Add location or placeholder
  if (locationofitem) {
    uniqueId += locationofitem.trim();
  } else {
    uniqueId += '--';
  }
  uniqueId += '/';
  
  // Add global serial number
  uniqueId += serialNumberStr;
  
  return uniqueId;
};

// @desc    Create inventory item
// @route   POST /api/inventory
// @access  Private (Admin/Stock Manager)
const createInventoryItem = asyncHandler(async (req, res) => {
  // Validate location if provided
  if (req.body.locationid) {
    const location = await Location.findById(req.body.locationid);
    if (!location) {
      return res.status(400).json({
        success: false,
        message: 'Invalid location ID'
      });
    }
    if (!location.isActive) {
      return res.status(400).json({
        success: false,
        message: 'Cannot assign item to inactive location'
      });
    }
  }

  // ALWAYS generate unique ID automatically with global serial number
  // Serial numbers are system-generated and cannot be manually set
  // This ensures sequential numbering based on asset count
  // Any manually provided uniqueid is ignored - system always generates it
  
  // Ensure counter is initialized/synced with actual inventory count
  const currentCounter = await SerialNumberCounter.getCurrentSequence();
  if (currentCounter === 0) {
    // Sync counter with actual inventory count if it's not initialized
    const totalItems = await InventoryItem.countDocuments();
    if (totalItems > 0) {
      await SerialNumberCounter.findByIdAndUpdate(
        'global',
        { sequenceValue: totalItems },
        { upsert: true, new: true }
      );
    }
  }
  
  // Always generate unique ID using global serial number (automatic, no manual input allowed)
  // The serial number is automatically incremented based on total asset count
  let uniqueId = await generateUniqueIdWithGlobalSerial(
    req.body.financialyear,
    req.body.assetname || req.body.assetnamefromcategory,
    req.body.locationofitem
  );
  
  // Verify the generated unique ID doesn't already exist (shouldn't happen, but safety check)
  const existingItem = await InventoryItem.findOne({ 
    uniqueid: uniqueId.toUpperCase().trim() 
  });
  
  if (existingItem) {
    // This is a rare race condition - regenerate with next number
    console.warn('Generated unique ID already exists, regenerating:', uniqueId);
    uniqueId = await generateUniqueIdWithGlobalSerial(
      req.body.financialyear,
      req.body.assetname || req.body.assetnamefromcategory,
      req.body.locationofitem
    );
  }

  // Convert empty productserialnumber to undefined to avoid validation issues
  const productserialnumber = req.body.productserialnumber?.trim();
  
  const inventoryData = {
    ...req.body,
    uniqueid: uniqueId,
    productserialnumber: productserialnumber && productserialnumber !== '' ? productserialnumber : undefined,
    createdby: req.user.id,
    lastmodifiedby: req.user.name
  };

  // Create inventory item
  // Note: productserialnumber is optional and can have duplicates
  let inventoryItem;
  try {
    inventoryItem = await InventoryItem.create(inventoryData);
  } catch (error) {
    // Handle MongoDB duplicate key error - only uniqueid should be unique
    if (error.code === 11000 && error.keyPattern && error.keyPattern.uniqueid) {
      return res.status(400).json({
        success: false,
        message: `Unique ID already exists: ${inventoryData.uniqueid}`
      });
    }
    // For all other errors (including any unexpected productserialnumber errors), re-throw
    // This will be handled by the asyncHandler error middleware
    throw error;
  }

  // Update location occupancy if location is specified
  if (inventoryItem.locationid) {
    try {
      const location = await Location.findById(inventoryItem.locationid);
      if (location) {
        await location.incrementOccupancy(inventoryItem.quantityperitem);
      }
    } catch (error) {
      console.error('Error updating location occupancy:', error);
    }
  }

  // Create initial transaction record
  await InventoryTransaction.create({
    inventoryitemid: inventoryItem._id,
    transactiontype: 'purchase',
    quantity: inventoryItem.quantityperitem,
    previousquantity: 0,
    newquantity: inventoryItem.balancequantityinstock,
    issuedby: req.user.id,
    purpose: 'Initial Purchase',
    notes: 'Item added to inventory',
    status: 'completed'
  });

  const populatedItem = await InventoryItem.findById(inventoryItem._id)
    .populate('assetcategoryid', 'name type')
    .populate('assetid', 'name description')
    .populate('locationid', 'name description address building floor')
    .populate('createdby', 'name email');

  await logAssetAudit({
    inventoryItemId: inventoryItem._id,
    assetUniqueId: inventoryItem.uniqueid,
    action: 'item_created',
    req,
    remarks: 'Asset registered in inventory',
    metadata: { assetname: inventoryItem.assetname },
  });

  res.status(201).json({
    success: true,
    message: 'Inventory item created successfully',
    data: populatedItem
  });
});

// @desc    Update inventory item
// @route   PUT /api/inventory/:id
// @access  Private (Admin/Stock Manager)
const updateInventoryItem = asyncHandler(async (req, res) => {
  const inventoryItem = await InventoryItem.findById(req.params.id);

  if (!inventoryItem) {
    return res.status(404).json({
      success: false,
      message: 'Inventory item not found'
    });
  }

  const bodyKeys = Object.keys(req.body).filter((k) => req.body[k] !== undefined);
  const beforeVals = {};
  bodyKeys.forEach((key) => {
    beforeVals[key] = inventoryItem[key];
  });

  // Update fields
  Object.keys(req.body).forEach(key => {
    if (req.body[key] !== undefined) {
      // Convert empty productserialnumber to undefined
      if (key === 'productserialnumber') {
        const value = req.body[key]?.trim();
        inventoryItem[key] = value && value !== '' ? value : undefined;
      } else {
        inventoryItem[key] = req.body[key];
      }
    }
  });

  if (req.body.financialyear !== undefined && inventoryItem.uniqueid) {
    const uniqueIdParts = inventoryItem.uniqueid.toUpperCase().split('/');
    if (uniqueIdParts.length === 5) {
      uniqueIdParts[1] = String(inventoryItem.financialyear).toUpperCase().trim();
      inventoryItem.uniqueid = uniqueIdParts.join('/');
    }
  }

  inventoryItem.lastmodifiedby = req.user.name;
  inventoryItem.lastmodifieddate = new Date();

  await inventoryItem.save();

  const serializeAuditValue = (val) => {
    if (val === undefined || val === null) return null;
    if (val instanceof Date) return val.toISOString();
    if (typeof val === 'object' && val !== null && val._id) return String(val._id);
    return val;
  };
  const auditValuesEqual = (a, b) =>
    JSON.stringify(serializeAuditValue(a)) === JSON.stringify(serializeAuditValue(b));

  const changes = [];
  bodyKeys.forEach((key) => {
    const from = beforeVals[key];
    const to = inventoryItem[key];
    if (!auditValuesEqual(from, to)) {
      changes.push({ field: key, from: serializeAuditValue(from), to: serializeAuditValue(to) });
    }
  });

  if (changes.length) {
    await logAssetAudit({
      inventoryItemId: inventoryItem._id,
      assetUniqueId: inventoryItem.uniqueid,
      action: 'item_updated',
      req,
      changes,
      remarks: '',
      metadata: { changeCount: changes.length },
    });
  }

  const populatedItem = await InventoryItem.findById(inventoryItem._id)
    .populate('assetcategoryid', 'name type')
    .populate('assetid', 'name description')
    .populate('locationid', 'name description address building floor')
    .populate('createdby', 'name email');

  res.json({
    success: true,
    message: 'Inventory item updated successfully',
    data: populatedItem
  });
});

// @desc    Delete inventory item
// @route   DELETE /api/inventory/:id?force=true
// @access  Private (Admin, Stock Manager)
const deleteInventoryItem = asyncHandler(async (req, res) => {
  const inventoryItem = await InventoryItem.findById(req.params.id);

  if (!inventoryItem) {
    return res.status(404).json({
      success: false,
      message: 'Inventory item not found'
    });
  }

  const forceDelete =
    req.query.force === 'true' ||
    req.query.force === '1' ||
    String(req.query.force || '').toLowerCase() === 'true';

  const isIssued = inventoryItem.status === 'issued';

  if (isIssued && !forceDelete) {
    return res.status(400).json({
      success: false,
      code: 'ITEM_IN_USE',
      message:
        'This asset is currently issued. To remove it from inventory you must confirm a full purge: all transactions, audit history, linked requests, and return requests for this asset will be permanently deleted.',
      details: {
        status: inventoryItem.status,
        issuedto: inventoryItem.issuedto || null,
        uniqueid: inventoryItem.uniqueid,
      },
    });
  }

  const itemId = inventoryItem._id;

  const session = await mongoose.startSession();
  try {
    await session.withTransaction(async () => {
      await AssetAuditLog.deleteMany({ inventoryitemid: itemId }, { session });
      await InventoryTransaction.deleteMany({ inventoryitemid: itemId }, { session });
      await Request.deleteMany({ inventoryitemid: itemId }, { session });
      await ReturnRequest.deleteMany({ inventoryitemid: itemId }, { session });
      await InventoryItem.findByIdAndDelete(itemId, { session });
    });

    res.json({
      success: true,
      message: 'Inventory item and all related records deleted successfully',
    });
  } catch (error) {
    console.error('Error during cascade delete:', error);
    res.status(500).json({
      success: false,
      message: 'Error deleting inventory item and related records',
    });
  } finally {
    await session.endSession();
  }
});

// @desc    Return inventory item
// @route   POST /api/inventory/:id/return
// @access  Private (Admin/Stock Manager)
const returnInventoryItem = asyncHandler(async (req, res) => {
  const { notes, condition } = req.body;

  const inventoryItem = await InventoryItem.findById(req.params.id);

  if (!inventoryItem) {
    return res.status(404).json({
      success: false,
      message: 'Inventory item not found'
    });
  }

  if (inventoryItem.status !== 'issued') {
    return res.status(400).json({
      success: false,
      message: 'Item is not currently issued'
    });
  }

  // Return the item
  await inventoryItem.returnItem(req.user.name);

  // Create transaction record
  const transaction = await InventoryTransaction.create({
    inventoryitemid: inventoryItem._id,
    transactiontype: 'return',
    quantity: 1,
    previousquantity: inventoryItem.balancequantityinstock - 1,
    newquantity: inventoryItem.balancequantityinstock,
    issuedby: req.user.id,
    purpose: 'Item Return',
    notes: notes || 'Item returned to inventory',
    condition: condition || 'excellent',
    actualreturndate: new Date(),
    status: 'completed'
  });

  const populatedItem = await InventoryItem.findById(inventoryItem._id)
    .populate('assetcategoryid', 'name type')
    .populate('assetid', 'name description')
    .populate('createdby', 'name email');

  res.json({
    success: true,
    message: 'Item returned successfully',
    data: {
      item: populatedItem,
      transaction
    }
  });
});

// @desc    Get available inventory items
// @route   GET /api/inventory/available
// @access  Private
const getAvailableInventoryItems = asyncHandler(async (req, res) => {
  const inventoryItems = await InventoryItem.findAvailable()
    .populate('assetcategoryid', 'name type')
    .populate('assetid', 'name description')
    .populate('locationid', 'name description address building floor')
    .sort({ assetname: 1 });

  res.json({
    success: true,
    count: inventoryItems.length,
    data: inventoryItems
  });
});

// @desc    Get low stock items
// @route   GET /api/inventory/low-stock
// @access  Private
const getLowStockItems = asyncHandler(async (req, res) => {
  const inventoryItems = await InventoryItem.findLowStock()
    .populate('assetcategoryid', 'name type')
    .populate('assetid', 'name description')
    .populate('locationid', 'name description address building floor')
    .sort({ balancequantityinstock: 1 });

  res.json({
    success: true,
    count: inventoryItems.length,
    data: inventoryItems
  });
});

// @desc    Get issued items
// @route   GET /api/inventory/issued
// @access  Private
const getIssuedItems = asyncHandler(async (req, res) => {
  const inventoryItems = await InventoryItem.findIssued()
    .populate('assetcategoryid', 'name type')
    .populate('assetid', 'name description')
    .populate('locationid', 'name description address building floor')
    .sort({ issueddate: -1 });

  res.json({
    success: true,
    count: inventoryItems.length,
    data: inventoryItems
  });
});

// @desc    Get inventory statistics
// @route   GET /api/inventory/stats
// @access  Private
const getInventoryStats = asyncHandler(async (req, res) => {
  const stats = await InventoryItem.aggregate([
    {
      $group: {
        _id: '$status',
        count: { $sum: 1 },
        totalValue: { $sum: '$totalcost' },
        totalQuantity: { $sum: '$balancequantityinstock' }
      }
    }
  ]);

  const totalItems = await InventoryItem.countDocuments();
  const totalValue = await InventoryItem.aggregate([
    { $group: { _id: null, total: { $sum: '$totalcost' } } }
  ]);

  const lowStockItems = await InventoryItem.findLowStock();

  res.json({
    success: true,
    data: {
      totalItems,
      totalValue: totalValue[0]?.total || 0,
      lowStockCount: lowStockItems.length,
      byStatus: stats
    }
  });
});

// @desc    Get inventory transactions
// @route   GET /api/inventory/:id/transactions
// @access  Private
const getInventoryTransactions = asyncHandler(async (req, res) => {
  const page = parseInt(req.query.page) || 1;
  const limit = parseInt(req.query.limit) || 10;
  const skip = (page - 1) * limit;

  const transactions = await InventoryTransaction.findByItem(req.params.id)
    .populate('issuedto', 'name email')
    .populate('issuedby', 'name email')
    .populate('approvedby', 'name email')
    .skip(skip)
    .limit(limit);

  const total = await InventoryTransaction.countDocuments({ inventoryitemid: req.params.id });

  res.json({
    success: true,
    count: transactions.length,
    total,
    page,
    pages: Math.ceil(total / limit),
    data: transactions
  });
});

// @desc    Bulk update inventory items
// @route   PUT /api/inventory/bulk-update
// @access  Private (Admin/Stock Manager)
const bulkUpdateInventoryItems = asyncHandler(async (req, res) => {
  const { items, updates } = req.body;

  if (!items || !Array.isArray(items) || items.length === 0) {
    return res.status(400).json({
      success: false,
      message: 'Items array is required'
    });
  }

  const results = [];
  const errors = [];

  for (const itemId of items) {
    try {
      const inventoryItem = await InventoryItem.findById(itemId);

      if (!inventoryItem) {
        errors.push({ itemId, error: 'Item not found' });
        continue;
      }

      // Update fields
      Object.keys(updates).forEach(key => {
        if (updates[key] !== undefined) {
          inventoryItem[key] = updates[key];
        }
      });

      inventoryItem.lastmodifiedby = req.user.name;
      inventoryItem.lastmodifieddate = new Date();

      await inventoryItem.save();
      results.push(inventoryItem);
    } catch (error) {
      errors.push({ itemId, error: error.message });
    }
  }

  res.json({
    success: true,
    message: `Updated ${results.length} items successfully`,
    data: {
      updated: results.length,
      errors: errors.length,
      results,
      errors
    }
  });
});

// @desc    Get next serial number preview (current sequence + 1, read-only)
// @route   GET /api/inventory/next-serial-preview
// @access  Private
const getNextSerialPreview = asyncHandler(async (req, res) => {
  try {
    // Always sync counter with actual inventory count to ensure accuracy
    const totalItems = await InventoryItem.countDocuments();
    
    // Get current counter value
    let currentSequence = await SerialNumberCounter.getCurrentSequence();
    
    // If counter is less than actual item count, sync it
    // This handles cases where items were created before the counter system
    if (currentSequence < totalItems) {
      await SerialNumberCounter.findByIdAndUpdate(
        'global',
        { sequenceValue: totalItems },
        { upsert: true, new: true }
      );
      currentSequence = totalItems;
    }
    
    const nextSerial = currentSequence + 1;
    const nextSerialFormatted = nextSerial.toString().padStart(3, '0');
    
    res.json({
      success: true,
      data: {
        currentSequence,
        nextSerial,
        nextSerialFormatted
      }
    });
  } catch (error) {
    console.error('Error getting serial preview:', error);
    // Fallback: use inventory count directly
    try {
      const totalItems = await InventoryItem.countDocuments();
      const nextSerial = totalItems + 1;
      res.json({
        success: true,
        data: {
          currentSequence: totalItems,
          nextSerial,
          nextSerialFormatted: nextSerial.toString().padStart(3, '0')
        }
      });
    } catch (countError) {
      // Final fallback
      res.json({
        success: true,
        data: {
          currentSequence: 0,
          nextSerial: 1,
          nextSerialFormatted: '001'
        }
      });
    }
  }
});

// @desc    Get available asset names for requests (excluding pending/approved requests)
// @route   GET /api/inventory/available-asset-names
// @access  Private
const getAvailableAssetNames = asyncHandler(async (req, res) => {
  const Request = require('../models/Request');

  // Get all pending and approved requests to exclude their item types
  const pendingAndApprovedRequests = await Request.find({
    status: { $in: ['pending', 'approved'] }
  }).select('itemtype');

  // Create a set of item types that are currently requested or approved
  const requestedItemTypes = new Set(
    pendingAndApprovedRequests.map(req => req.itemtype.trim().toLowerCase())
  );

  // Get all available inventory items
  const availableItems = await InventoryItem.find({
    status: 'available',
    balancequantityinstock: { $gt: 0 }
  }).select('assetname');

  // Extract unique asset names
  const allAssetNames = new Set();
  availableItems.forEach(item => {
    if (item.assetname && item.assetname.trim()) {
      allAssetNames.add(item.assetname.trim());
    }
  });

  // Filter out asset names that have pending or approved requests
  const availableAssetNames = Array.from(allAssetNames).filter(
    assetName => !requestedItemTypes.has(assetName.toLowerCase())
  ).sort();

  res.json({
    success: true,
    count: availableAssetNames.length,
    data: availableAssetNames
  });
});

function formatUserSnapshot(u) {
  if (!u) return null;
  if (typeof u === 'object') {
    return {
      name: u.name || '—',
      email: u.email || '—',
      role: u.role || null,
      department: u.department || null,
    };
  }
  return { name: String(u), email: null, role: null, department: null };
}

function humanTransactionSummary(t) {
  const type = t.transactiontype;
  const assignee = t.issuedto && typeof t.issuedto === 'object' ? t.issuedto.name : null;
  if (type === 'issue') return assignee ? `Issued to ${assignee}` : 'Issued to assignee';
  if (type === 'return') return assignee ? `Return processed (${assignee})` : 'Returned to inventory';
  if (type === 'purchase') return 'Initial receipt / added to inventory';
  if (type === 'adjustment') return 'Stock adjustment';
  if (type === 'disposal') return 'Disposal';
  if (type === 'maintenance') return 'Maintenance';
  return `Transaction: ${type}`;
}

function humanAuditSummary(a) {
  const map = {
    item_created: 'Asset created',
    item_updated: 'Asset details updated',
    item_deleted: 'Asset deleted from inventory',
  };
  return map[a.action] || a.action.replace(/_/g, ' ');
}

// @desc    Chronological audit history (transactions + structured audit log)
// @route   GET /api/inventory/:id/audit-history
// @access  Private (Admin, Stock Manager)
const getAssetAuditHistory = asyncHandler(async (req, res) => {
  let item = await InventoryItem.findById(req.params.id).select('uniqueid assetname');
  const rawUniqueId =
    (typeof req.query.uniqueId === 'string' && req.query.uniqueId.trim()) ||
    (typeof req.query.uniqueid === 'string' && req.query.uniqueid.trim()) ||
    '';
  const qUnique = String(rawUniqueId).trim();

  const escapeRegex = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const uniqueIdPattern = qUnique
    ? new RegExp(`^${escapeRegex(qUnique).replace(/\s+/g, '\\s+')}$`, 'i')
    : null;

  if (!item && qUnique) {
    item = await InventoryItem.findOne({
      $or: [{ uniqueid: qUnique }, { uniqueid: uniqueIdPattern }],
    }).select('uniqueid assetname');
  }
  if (!item) {
    return res.status(404).json({
      success: false,
      message: 'Inventory item not found',
    });
  }

  const itemId = item._id;

  const [audits, txs] = await Promise.all([
    AssetAuditLog.find({ inventoryitemid: itemId }).sort({ occurredAt: 1 }).lean(),
    InventoryTransaction.find({ inventoryitemid: itemId })
      .sort({ transactiondate: 1, createdAt: 1 })
      .populate('issuedto', 'name email department role')
      .populate('issuedby', 'name email department role')
      .lean(),
  ]);

  const events = [];

  txs.forEach((t) => {
    events.push({
      source: 'transaction',
      id: String(t._id),
      at: t.transactiondate || t.createdAt,
      kind: t.transactiontype,
      summary: humanTransactionSummary(t),
      actor: formatUserSnapshot(t.issuedby),
      assignee: formatUserSnapshot(t.issuedto),
      quantity: t.quantity,
      previousQuantity: t.previousquantity,
      newQuantity: t.newquantity,
      purpose: t.purpose || null,
      remarks: t.notes || null,
      transactionStatus: t.status,
      condition: t.condition || null,
      expectedReturnDate: t.expectedreturndate || null,
      actualReturnDate: t.actualreturndate || null,
    });
  });

  audits.forEach((a) => {
    events.push({
      source: 'audit',
      id: String(a._id),
      at: a.occurredAt,
      kind: a.action,
      summary: humanAuditSummary(a),
      actor: a.actor,
      subject: a.subject || null,
      changes: a.changes || [],
      remarks: a.remarks || null,
      metadata: a.metadata || null,
    });
  });

  events.sort((x, y) => new Date(x.at) - new Date(y.at));

  res.json({
    success: true,
    data: {
      inventoryItemId: String(item._id),
      uniqueid: item.uniqueid,
      assetname: item.assetname,
      events,
    },
  });
});

module.exports = {
  getInventoryItems,
  getInventoryItem,
  createInventoryItem,
  updateInventoryItem,
  deleteInventoryItem,
  returnInventoryItem,
  getAvailableInventoryItems,
  getLowStockItems,
  getIssuedItems,
  getInventoryStats,
  getInventoryTransactions,
  bulkUpdateInventoryItems,
  getAvailableAssetNames,
  getNextSerialPreview,
  getAssetAuditHistory,
};
